# Generated by Django 4.2.2 on 2023-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_dis', models.TextField()),
                ('receipe_img', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
